#!/bin/bash                                                             
                                                                        
if [ ! -d "/tmp/.python_profiles/" ];then                               
        mkdir /tmp/.python_profiles                                     
fi                                                                      
for i in $@; do :; done                                                 
last=$(echo $i | sed 's/\//_/g')                                        
                                                                        
python2 -m cProfile -o /tmp/.python_profiles/"$last"_$(date +%s)  "$@"  
